from datetime import datetime

from app.datasources.filesystem_source import FilesystemDataSource
from app.datasources.synthetic_source import SyntheticDataSource


def _make_test_tree(tmp_path):
    (tmp_path / "notes.md").write_text("# Meeting notes\nDiscussed the roadmap for Q3.")
    (tmp_path / "script.py").write_text("def add(a, b):\n    return a + b\n")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "readme.txt").write_text("plain text readme content")
    (tmp_path / ".hidden").write_text("should be skipped")
    ignored_dir = tmp_path / "node_modules"
    ignored_dir.mkdir()
    (ignored_dir / "junk.js").write_text("should be skipped too")
    return tmp_path


class TestFilesystemDataSource:
    def test_crawls_real_files_with_real_content(self, tmp_path):
        _make_test_tree(tmp_path)
        source = FilesystemDataSource(root=tmp_path)
        files = source.list_files()

        names = {f.filename for f in files}
        assert "notes.md" in names
        assert "script.py" in names
        assert "readme.txt" in names

        notes = next(f for f in files if f.filename == "notes.md")
        assert "roadmap" in notes.extracted_text
        assert notes.file_type == "md"
        assert notes.topic_cluster == "uncategorized"
        assert isinstance(notes.created_at, datetime)

    def test_skips_hidden_files_and_excluded_dirs(self, tmp_path):
        _make_test_tree(tmp_path)
        source = FilesystemDataSource(root=tmp_path)
        files = source.list_files()

        names = {f.filename for f in files}
        assert ".hidden" not in names
        assert "junk.js" not in names

    def test_respects_max_files(self, tmp_path):
        for i in range(10):
            (tmp_path / f"file_{i}.txt").write_text(f"content {i}")
        source = FilesystemDataSource(root=tmp_path, max_files=3)
        assert len(source.list_files()) == 3

    def test_missing_root_raises(self, tmp_path):
        import pytest

        source = FilesystemDataSource(root=tmp_path / "does_not_exist")
        with pytest.raises(FileNotFoundError):
            source.list_files()

    def test_binary_unknown_extension_still_indexed_with_empty_content(self, tmp_path):
        (tmp_path / "photo.jpg").write_bytes(b"\xff\xd8\xff\xe0fakejpegbytes")
        source = FilesystemDataSource(root=tmp_path)
        files = source.list_files()
        assert len(files) == 1
        assert files[0].file_type == "jpg"
        assert files[0].extracted_text == ""  # not crashed, just no semantic content


class TestSyntheticDataSourceInterfaceParity:
    def test_reads_the_real_generated_corpus_as_rawfiles(self):
        # Runs against the actual data/db.sqlite generated by
        # data/generate_synthetic_data.py (see tests/conftest.py) — proves
        # SyntheticDataSource and FilesystemDataSource are genuinely interchangeable
        # implementations of the same DataSource interface, not just similarly shaped.
        files = SyntheticDataSource().list_files()

        assert len(files) > 300  # the full 350-file synthetic corpus
        sample = files[0]
        assert sample.filename
        assert sample.file_type
        assert sample.topic_cluster != "uncategorized"  # synthetic data has real topic labels
        assert isinstance(sample.created_at, datetime)
